import Overlay from "@/component/overlay"
import HeadDupla from "@/component/headDupla"
import styles from '@/styles/Home.module.css'
import  Head from 'next/head'

export default function Video() {
    return (
      <>
      <Head>
        <title>Ailton santos e Valter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&family=Madimi+One&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <video className={styles.video} autoPlay muted loop><source src="/justo.mp4"/></video>
            <Overlay />
      <main className={styles.principal} >
            <HeadDupla />
      </main>
        
        
        
        </>
    )
       
           
  }